src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Line Item</label>
        <referenceTo>Line_Item__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewOrderCtrl.cls
/* This is controller for the NewOrder vf-page.
 * @author Pavel Trusov
 */
public class NewOrderCtrl {

  public Contact newContact {get; set;}  
  public Line_Item__c newLineItem {get; set;}   
  public Order__c newOrder {get; set;} 
  public Id recordId {get; set;}
  public Merchandise__c selectedProduct {get; set;}

  /* Save button. Inserts data from variables into the sObjects.
   * Returns the user to the ClientSheet page upon completion. */
  public PageReference save() {
    insert this.newContact;
    this.newLineItem.Merchandise__c = this.selectedProduct.Id;
    insert this.newLineItem;
    this.newOrder.Contact__c = this.newContact.Id;
    this.newOrder.Line_Item__c = this.newLineItem.Id;
    insert this.newOrder;
    return Page.ClientSheet;
  }

  /* NewOrderCtrl constructor. */     
  public NewOrderCtrl() {
    /* Gets recordId from vf-page URL.*/
    this.recordId = ApexPages.currentPage().getParameters().get(CountSheetCtrl.PARAMETER_ID);
    /* Selects a record with current recordId. */
    this.selectedProduct = [SELECT Id, Name FROM Merchandise__c 
                                  WHERE Id = :this.recordId LIMIT 1];
    this.newOrder = new Order__c();
    this.newLineItem = new Line_Item__c();
    this.newContact = new Contact();
  }
}