src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewOrderCtrlTest.cls
/* Test unit to cover NewOrderCtrl
 * @author Pavel Trusov
 */
@isTest
public class NewOrderCtrlTest {
	static testMethod void orderTest() {
		Test.setCurrentPage(Page.NewOrder);
		Merchandise__c testProduct = new Merchandise__c(Name = 'Test', 
											Quantity__c = 100, Price__c = 100);
		insert testProduct;
		ApexPages.currentPage().getParameters().put(CountSheetCtrl.PARAMETER_ID, testProduct.Id);
		Test.startTest();
		NewOrderCtrl controller = new NewOrderCtrl();
		controller.newContact.FirstName = 'Test';
		controller.newContact.LastName = 'Test'; 
		controller.newContact.Email = 'Test@test.com';
		controller.newLineItem.Quantity__c = 100;
		controller.save();
		Test.stopTest();
		System.assert([SELECT Id FROM Order__c].size() > 0);
	}
}