src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewProductCtrlTest.cls
/* Test unit to cover NewProductCtrl
 * @author Pavel Trusov
 */
@isTest
private class NewProductCtrlTest {
	static testMethod void productTest() {
		Test.startTest();
		NewProductCtrl controller = new NewProductCtrl();
		controller.newRecord.Name = 'Test';
		controller.newRecord.Quantity__c = 100;
		controller.newRecord.Price__c = 100;
		controller.save();
		System.assert([SELECT Id FROM Merchandise__c].size() > 0);
		System.assert(controller.save() == null);
		Test.stopTest();
	}
}