src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CountSheetCtrlTest.cls
/* Test unit to cover CountSheetCtrl
 * @author Pavel Trusov
 */
@isTest
public class CountSheetCtrlTest {
	static testMethod void productsTest() {
		Merchandise__c testProduct = new Merchandise__c(Name = 'Test', 
											Quantity__c = 100, Price__c = 100);
		insert testProduct;
		Test.startTest();
		CountSheetCtrl prods = new CountSheetCtrl();
		System.assert(prods != null);
    	System.assert(prods.products.size() > 0);
    	prods.recordId = testProduct.Id;
    	System.assert(prods.newRecord() != null);
    	System.assert(prods.newOrder().getParameters().get(CountSheetCtrl.PARAMETER_ID) == testProduct.Id);
    	prods.deleteRecord();
    	System.assert([SELECT Id FROM Merchandise__c].size() == 0);
    	Test.stopTest();
	}
}